log_header("DOM Features");

log("Core 1.0 : " + document.implementation.hasFeature("Core", "1.0"));
log("Core 2.0 : " + document.implementation.hasFeature("Core", "2.0"));
log("Core 3.0 : " + document.implementation.hasFeature("Core", "3.0"));
log("XML 1.0 : " + document.implementation.hasFeature("XML", "1.0"));
log("XML 2.0 : " + document.implementation.hasFeature("XML", "2.0"));
log("XML 3.0 : " + document.implementation.hasFeature("XML", "3.0"));
log("HTML 1.0 : " + document.implementation.hasFeature("HTML", "1.0"));
log("HTML 2.0 : " + document.implementation.hasFeature("HTML", "2.0"));
log("Views 2.0 : " + document.implementation.hasFeature("Views", "2.0"));
log("StyleSheets 2.0 : " + document.implementation.hasFeature("StyleSheets", "2.0"));
log("CSS 2.0 : " + document.implementation.hasFeature("CSS", "2.0"));
log("CSS2 2.0 : " + document.implementation.hasFeature("CSS2", "2.0"));
log("Events 2.0 : " + document.implementation.hasFeature("Events", "2.0"));
log("Events 3.0 : " + document.implementation.hasFeature("Events", "3.0"));
log("UIEvents 2.0 : " + document.implementation.hasFeature("UIEvents", "2.0"));
log("UIEvents 3.0 : " + document.implementation.hasFeature("UIEvents", "3.0"));
log("MouseEvents 2.0 : " + document.implementation.hasFeature("MouseEvents", "2.0"));
log("MouseEvents 3.0 : " + document.implementation.hasFeature("MouseEvents", "3.0"));
log("MutationEvents 2.0 : " + document.implementation.hasFeature("MutationEvents", "2.0"));
log("MutationEvents 3.0 : " + document.implementation.hasFeature("MutationEvents", "3.0"));
log("HTMLEvents 2.0 : " + document.implementation.hasFeature("HTMLEvents", "2.0"));
log("Range 2.0 : " + document.implementation.hasFeature("Range", "2.0"));
log("Traversal 2.0 : " + document.implementation.hasFeature("Traversal", "2.0"));
log("LS 3.0 : " + document.implementation.hasFeature("LS", "3.0"));
log("LS-Async 3.0 : " + document.implementation.hasFeature("LS-Async", "3.0"));
log("Validation 3.0 : " + document.implementation.hasFeature("Validation", "3.0"));